name: CI/CD with GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      ## Checkout code repository
      - name: Checkout Code
        uses: actions/checkout@v3

      ## Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      ## Install dependencies
      - name: Install Dependencies
        run: bun install

      ## Build Project
      - name: Build Project
        run: bun run build
        env:
          BASE_URL: /portfolio/

      ## Deploy to github pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
